In [2]:
import os
import pandas as pd

In [5]:
df = pd.read_csv('base_completa.csv')
df

,TIPREG,DATA,CODBDI,CODNEG,TPMERC,NOMRES,ESPECI,PRAZOT,MODREF,PREABE,...,TOTNEG,QUATOT,VOLTOT,PREEXE,INDOPC,DATVEN,FATCOT,PTOEXE,CODISI,DISMES
0,1,2020-01-02,2,AALR3,10,ALLIAR,ON NM,NaN,R$,1829.0,...,2443,585800,1.094620e+09,0.0,0,99991231,1,0.0,BRAALRACNOR6,101
1,1,2020-01-02,2,AAPL34,10,APPLE,DRN,NaN,R$,12000.0,...,9,12700,1.533380e+08,0.0,0,99991231,1,0.0,BRAAPLBDR004,131
2,1,2020-01-02,2,ABCB4,10,ABC BRASIL,PN EJ N2,NaN,R$,2000.0,...,3979,870400,1.745788e+09,0.0,0,99991231,1,0.0,BRABCBACNPR4,133
3,1,2020-01-02,2,ABEV3,10,AMBEV S/A,ON EJ,NaN,R$,1886.0,...,31581,16011300,3.062348e+10,0.0,0,99991231,1,0.0,BRABEVACNOR1,122
4,1,2020-01-02,2,ADHM3,10,ADVANCED-DH,ON,NaN,R$,255.0,...,307,193400,4.719270e+07,0.0,0,99991231,1,0.0,BRADHMACNOR9,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878139,1,2020-09-29,82,YDUQW320,80,YDUQE,ON NM,0.0,R$,515.0,...,4,2400,1.271400e+06,3200.0,0,20201116,1,0.0,BRYDUQACNOR3,101
878140,1,2020-09-29,82,YDUQV252,80,YDUQE,ON NM,0.0,R$,52.0,...,1,100,5.200000e+03,2525.0,0,20201019,1,0.0,BRYDUQACNOR3,101
878141,1,2020-09-29,82,YDUQV267,80,YDUQE FM,ON NM,0.0,R$,107.0,...,4,30200,3.189600e+06,2675.0,0,20201019,1,0.0,BRYDUQACNOR3,101
878142,1,2020-09-29,82,YDUQV275,80,YDUQE,ON NM,0.0,R$,142.0,...,29,37700,5.353700e+06,2750.0,0,20201019,1,0.0,BRYDUQACNOR3,101
878143,1,2020-09-29,82,YDUQV280,80,YDUQE FM,ON NM,0.0,R$,171.0,...,2,2000,3.398000e+05,2800.0,0,20201019,1,0.0,BRYDUQACNOR3,101

In [10]:
df['DATA'].value_counts().min()

3530

In [11]:
df['DATA'].value_counts().max()

6483

In [12]:
df.head()

,TIPREG,DATA,CODBDI,CODNEG,TPMERC,NOMRES,ESPECI,PRAZOT,MODREF,PREABE,...,TOTNEG,QUATOT,VOLTOT,PREEXE,INDOPC,DATVEN,FATCOT,PTOEXE,CODISI,DISMES
0,1,2020-01-02,2,AALR3,10,ALLIAR,ON NM,NaN,R$,1829.0,...,2443,585800,1.094620e+09,0.0,0,99991231,1,0.0,BRAALRACNOR6,101
1,1,2020-01-02,2,AAPL34,10,APPLE,DRN,NaN,R$,12000.0,...,9,12700,1.533380e+08,0.0,0,99991231,1,0.0,BRAAPLBDR004,131
2,1,2020-01-02,2,ABCB4,10,ABC BRASIL,PN EJ N2,NaN,R$,2000.0,...,3979,870400,1.745788e+09,0.0,0,99991231,1,0.0,BRABCBACNPR4,133
3,1,2020-01-02,2,ABEV3,10,AMBEV S/A,ON EJ,NaN,R$,1886.0,...,31581,16011300,3.062348e+10,0.0,0,99991231,1,0.0,BRABEVACNOR1,122
4,1,2020-01-02,2,ADHM3,10,ADVANCED-DH,ON,NaN,R$,255.0,...,307,193400,4.719270e+07,0.0,0,99991231,1,0.0,BRADHMACNOR9,101

In [13]:
df.tail()

,TIPREG,DATA,CODBDI,CODNEG,TPMERC,NOMRES,ESPECI,PRAZOT,MODREF,PREABE,...,TOTNEG,QUATOT,VOLTOT,PREEXE,INDOPC,DATVEN,FATCOT,PTOEXE,CODISI,DISMES
878139,1,2020-09-29,82,YDUQW320,80,YDUQE,ON NM,0.0,R$,515.0,...,4,2400,1271400.0,3200.0,0,20201116,1,0.0,BRYDUQACNOR3,101
878140,1,2020-09-29,82,YDUQV252,80,YDUQE,ON NM,0.0,R$,52.0,...,1,100,5200.0,2525.0,0,20201019,1,0.0,BRYDUQACNOR3,101
878141,1,2020-09-29,82,YDUQV267,80,YDUQE FM,ON NM,0.0,R$,107.0,...,4,30200,3189600.0,2675.0,0,20201019,1,0.0,BRYDUQACNOR3,101
878142,1,2020-09-29,82,YDUQV275,80,YDUQE,ON NM,0.0,R$,142.0,...,29,37700,5353700.0,2750.0,0,20201019,1,0.0,BRYDUQACNOR3,101
878143,1,2020-09-29,82,YDUQV280,80,YDUQE FM,ON NM,0.0,R$,171.0,...,2,2000,339800.0,2800.0,0,20201019,1,0.0,BRYDUQACNOR3,101